# For testers
# This file should be called with
# docker-compose -f test.yml up

version: '2'
services:
  odoo:
    image: camptocamp/demo_odoo:latest
    depends_on:
      - db
    volumes:
      - "data-odoo:/data/odoo"
    environment:
      - DB_USER=odoo
      - DB_PASSWORD=odoo
      - DB_NAME=odoodb
      - ADMIN_PASSWD=mijaebohb8Thae1g
      - RUNNING_ENV=dev
      - MARABUNTA_MODE=sample  # could be 'full' for the db with all the data
      - MARABUNTA_ALLOW_SERIE=True  # should not be set in production

  db:
    image: camptocamp/postgres:9.5
    command: -c shared_buffers=256MB -c maintenance_work_mem=256MB -c wal_buffers=8MB -c effective_cache_size=1024MB
    ports:
      - 5432
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - "data-db:/var/lib/postgresql/data"

  nginx:
    image: camptocamp/odoo-nginx:11.0-1.5.0
    depends_on:
      - odoo
    ports:
      - 80:80

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025

volumes:
  data-odoo:
  data-db:
